system: |-
  - Ubuntu
  - Conda (Python 3.12)
  - LAMMPS
files:
  - "lammps/create_network.py"
  - "lammps/spring_network.py"
  - "lammps/visualize_simulation.py"
  - "lammps/visualize_mesh.py"
  - "lammps/log_lammps.txt"
  - "lammps/log_springs.txt"
  - "code/main.cpp"
  - "code/CMakeLists.txt"
  - "tree.txt"
  - "README.md"
prompts:
  CodeChanges: "Do not copy the entire source code. Just give me the complete version of the modified members (functions, classes, ...) and explain where should I put them."
  CodeFull: "Write a complete updated source code."
  GitMessage: "Please write a clear, conventional commit message based on the following git_diff, which shows the STAGED changes:"